CREATE TABLE arquivos( 
    id INT NOT NULL AUTO_INCREMENT, 
    id_usuario INT NOT NULL, 
    arquivo VARCHAR(250) NOT NULL, 
    caminho VARCHAR(250) NOT NULL,
    tipo VARCHAR(250) NOT NULL,
    upload TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id), 
    FOREIGN KEY(id_usuario) REFERENCES usuarios(id)); 